name: Publish to TestPyPi

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Specify your Python version

    - name: Install Poetry
      run: pip install poetry

    - name: Configure Poetry
      run: |
        poetry config repositories.testpypi https://test.pypi.org/legacy/
        poetry config pypi-token.testpypi ${{ secrets.PYPI_TEST_TOKEN }}

    - name: Install dependencies
      run: poetry install

    - name: Build and publish package
      run: poetry publish --build -r testpypi
      env:
        POETRY_PYPI_TOKEN_TESTPYPI: ${{ secrets.PYPI_TEST_TOKEN }}
